### ISSUE TITLE
Error invoking callback

### ISSUE THREAD

**Issue by Waterovsky** [NockyCZ/CS2-ReservedSlots#7]
v1.0.7, css v233

```17:42:59 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: An item with the same key has already been added. Key: CounterStrikeSharp.API.Core.CCSPlayerController
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at ReservedSlots.ReservedSlots.PerformKick(CCSPlayerController player, KickReason reason) in C:\Users\Mates-PC\Desktop\SourceFactory\Projects\CSharp\ReservedSlots\ReservedSlots.cs:line 237
   at ReservedSlots.ReservedSlots.OnPlayerConnect(EventPlayerConnectFull event, GameEventInfo info) in C:\Users\Mates-PC\Desktop\SourceFactory\Projects\CSharp\ReservedSlots\ReservedSlots.cs:line 218
   at InvokeStub_GameEventHandler`1.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
```

**Comment by NockyCZ** [comment]
Fixed - https://github.com/NockyCZ/CS2-ReservedSlots/releases/tag/v1.0.8
